"""Project entry point for running the detector from the repository root."""

import csv
import re
import time
import threading
from datetime import datetime
from pathlib import Path
from typing import Literal, Optional

import pandas as pd
import pyodbc

from core.config import Config
from core.detector import DoorNumberDetector
from core.metrics import RunMetrics

import sys
if sys.stdout and hasattr(sys.stdout, "reconfigure"):
    sys.stdout.reconfigure(encoding="utf-8", errors="replace")


_OUTPUT_COLUMNS = [
    "LATITUDE",
    "LONGITUDE",
    "NOME_COMPLETO_PORTA",
    "PREDICTION",
    "CONFIDENCE",
    "PREDICTION_FOUND",
    "MATCH",
    "OBSERVATION",
]

_FILTER_COLUMNS = {
    "localidade": "NOME_LOCALIDADE",
    "freguesia":  "NOME_FREGUESIA",
    "concelho":   "NOME_CONCELHO",
    "rua":        "ID_RUA",
}

_NO_IMAGERY_TOKEN = "NO_IMAGERY"
_NO_IMAGERY_OBS   = "No Street View imagery available"


def _normalize(s: str) -> str:
    return re.sub(r"\s+", "", s.strip().upper())


# ── CSV helpers ────────────────────────────────────────────────────────────────

def _init_output_csv(output_path: Path) -> None:
    with open(output_path, "w", newline="", encoding="utf-8-sig") as f:
        csv.writer(f, delimiter=";").writerow(_OUTPUT_COLUMNS)


def _append_row_to_csv(output_path: Path, row_data: list) -> None:
    with open(output_path, "a", newline="", encoding="utf-8-sig") as f:
        csv.writer(f, delimiter=";").writerow(row_data)


def _load_already_processed(existing_csv: Path) -> set[tuple[float, float]]:
    processed = set()
    with open(existing_csv, newline="", encoding="utf-8-sig") as f:
        reader = csv.DictReader(f, delimiter=";")
        for row in reader:
            try:
                processed.add((float(row["LATITUDE"]), float(row["LONGITUDE"])))
            except (KeyError, ValueError):
                continue
    return processed


# ── Excel reading ──────────────────────────────────────────────────────────────

def _read_spreadsheetml(path: Path) -> pd.DataFrame:
    """Parse SpreadsheetML XML (.xls generated by browser JS) into a DataFrame."""
    import xml.etree.ElementTree as ET
    NS = "urn:schemas-microsoft-com:office:spreadsheet"
    rows_data = []
    for row_elem in ET.parse(str(path)).getroot().iter(f"{{{NS}}}Row"):
        row_vals = []
        for cell_elem in row_elem.findall(f"{{{NS}}}Cell"):
            data_elem = cell_elem.find(f"{{{NS}}}Data")
            row_vals.append(data_elem.text if data_elem is not None and data_elem.text else "")
        rows_data.append(row_vals)
    if not rows_data:
        raise ValueError("No data found in SpreadsheetML file")
    headers = rows_data[0]
    data    = [r + [""] * (len(headers) - len(r)) for r in rows_data[1:]]
    return pd.DataFrame(data, columns=headers)


def _read_excel_any(path: Path) -> pd.DataFrame:
    """Read .xlsx, binary .xls, or browser-generated SpreadsheetML .xls."""
    path = Path(path)
    with open(path, "rb") as f:
        peek = f.read(200).lstrip()
    if peek.startswith(b"<?xml") or peek.startswith(b"<Workbook"):
        return _read_spreadsheetml(path)
    engine = "openpyxl" if path.suffix.lower() == ".xlsx" else "xlrd"
    return pd.read_excel(path, engine=engine)


# ── SQL Server source ──────────────────────────────────────────────────────────

def _query_sqlserver(
    filter_by: Literal["localidade", "freguesia", "concelho", "rua"],
    filter_value: str,
    config: Config,
) -> pd.DataFrame:
    if filter_by not in _FILTER_COLUMNS:
        raise ValueError(
            f"filter_by must be one of {list(_FILTER_COLUMNS.keys())}, got '{filter_by}'"
        )

    column = _FILTER_COLUMNS[filter_by]

    if config.src_db_trusted:
        conn_str = (
            f"DRIVER={{{config.src_db_driver}}};"
            f"SERVER={config.src_db_server};"
            f"DATABASE={config.src_db_database};"
            "Trusted_Connection=yes;"
        )
    else:
        conn_str = (
            f"DRIVER={{{config.src_db_driver}}};"
            f"SERVER={config.src_db_server};"
            f"DATABASE={config.src_db_database};"
            f"UID={config.src_db_user};"
            f"PWD={config.src_db_password};"
        )

    query = f"""
        SELECT
            NOME_COMPLETO_PORTA,
            LAT  AS LATITUDE,
            LON  AS LONGITUDE
        FROM [GEO_DB].[SGM].[SGM_PORTA]
        WHERE {column} = ?
          AND LAT IS NOT NULL
          AND LON IS NOT NULL
          AND ESTADO_PORTA NOT IN (N'Sinónimo', N'Apagado')
    """

    print(f"Connecting to {config.src_db_server} / {config.src_db_database} ...")
    print(f"Filter: {column} = '{filter_value}'")
    conn = pyodbc.connect(conn_str, timeout=30)
    try:
        df = pd.read_sql(query, conn, params=[filter_value])
    finally:
        conn.close()

    if df.empty:
        raise ValueError(f"No rows found for {column} = '{filter_value}'")

    df["LATITUDE"]  = pd.to_numeric(df["LATITUDE"],  errors="coerce")
    df["LONGITUDE"] = pd.to_numeric(df["LONGITUDE"], errors="coerce")
    df = df.dropna(subset=["LATITUDE", "LONGITUDE"]).reset_index(drop=True)

    print(f"Loaded {len(df)} rows for {column} = '{filter_value}'")
    return df


# ── Core detection loop ────────────────────────────────────────────────────────

import logging
logger = logging.getLogger(__name__)

def _run_detection_on_df(
    df: pd.DataFrame,
    output_path: Path,
    already_processed: set[tuple[float, float]],
    existing_csv: Optional[Path] = None,
    detector_instance=None,
    cancel_event: Optional[threading.Event] = None,
    metrics: Optional[RunMetrics] = None,
) -> Path:
    df_todo = df[
        ~df.apply(
            lambda r: (
                not pd.isna(r["LATITUDE"])
                and not pd.isna(r["LONGITUDE"])
                and (float(r["LATITUDE"]), float(r["LONGITUDE"])) in already_processed
            ),
            axis=1,
        )
    ]

    skipped = len(df) - len(df_todo)
    if skipped:
        print(f"Skipping {skipped} already-processed row(s). {len(df_todo)} remaining.")

    if df_todo.empty:
        print("Nothing to process — all rows already in the existing CSV.")
        return existing_csv

    output_path.parent.mkdir(parents=True, exist_ok=True)
    _init_output_csv(output_path)

    if existing_csv is not None:
        with open(existing_csv, newline="", encoding="utf-8-sig") as src:
            reader = csv.DictReader(src, delimiter=";")
            for row in reader:
                _append_row_to_csv(output_path, [row.get(col, "") for col in _OUTPUT_COLUMNS])
        print(f"Copied {len(already_processed)} existing row(s) into {output_path.name}.")

    _owns_detector = detector_instance is None
    detector = detector_instance if detector_instance is not None else DoorNumberDetector()

    _owns_metrics = metrics is None
    if _owns_metrics:
        metrics = RunMetrics()

    total    = len(df_todo)
    n_match  = 0
    n_error  = 0
    n_no_img = 0
    i        = 0

    try:
        for i, (_, row) in enumerate(df_todo.iterrows(), 1):

            if cancel_event is not None and cancel_event.is_set():
                print(f"[{i}/{total}] Batch cancelled by user — stopping cleanly.")
                break

            nome      = str(row.get("NOME_COMPLETO_PORTA", "") or "").strip()
            latitude  = row.get("LATITUDE")
            longitude = row.get("LONGITUDE")

            prediction       = None
            confidence       = 0
            prediction_found = "NO"
            observation      = ""

            if pd.isna(latitude) or pd.isna(longitude):
                logger.warning(f"[{i}/{total}] Skipping row with null coordinates.")
            else:
                detector.street_view.reset_call_counts()
                t0 = time.process_time()

                _result_success = False
                _is_no_imagery  = False

                try:
                    result = detector.detect_door_number(
                        float(latitude), float(longitude),
                        cancel_event=cancel_event,
                    )

                    if cancel_event is not None and cancel_event.is_set():
                        print(f"[{i}/{total}] Cancelled mid-detection — stopping.")
                        break

                    observation    = result.get("observation", "")
                    _is_no_imagery = (observation == _NO_IMAGERY_OBS)

                    if _is_no_imagery:
                        prediction_found = _NO_IMAGERY_TOKEN
                        prediction       = None
                        confidence       = 0
                        n_no_img        += 1
                    else:
                        prediction_found = "YES" if result.get("success", False) else "NO"
                        prediction       = result.get("door_number") if prediction_found == "YES" else None
                        confidence       = result.get("confidence", 0)
                        _result_success  = result.get("success", False)

                except Exception as exc:
                    n_error += 1
                    logger.error(
                        f"[{i}/{total}] detect_door_number raised an exception "
                        f"at ({latitude}, {longitude}): {exc}",
                        exc_info=True,
                    )
                    _append_row_to_csv(
                        output_path,
                        [latitude, longitude, nome, None, 0, "NO", "NO", ""],
                    )
                    _img_e, _meta_e = detector.street_view.get_call_counts()
                    metrics.record(
                        elapsed_s=time.process_time() - t0,
                        image_calls=_img_e,
                        metadata_calls=_meta_e,
                        success=False,
                        no_imagery=False,
                    )
                    continue

                _img, _meta = detector.street_view.get_call_counts()
                metrics.record(
                    elapsed_s=time.process_time() - t0,
                    image_calls=_img,
                    metadata_calls=_meta,
                    success=_result_success,
                    no_imagery=_is_no_imagery,
                )

            match = "YES" if (
                prediction is not None
                and nome != ""
                and _normalize(prediction) == _normalize(nome)
            ) else "NO"
            if match == "YES":
                n_match += 1

            _append_row_to_csv(
                output_path,
                [latitude, longitude, nome, prediction, confidence, prediction_found, match, observation],
            )

            status = (
                "✓ MATCH"        if match == "YES" else
                "📷 NO IMAGERY"  if prediction_found == _NO_IMAGERY_TOKEN else
                "✗ WRONG"        if prediction_found == "YES" else
                "? NOT FOUND"
            )
            print(f"[{i}/{total}] expected={nome!r} predicted={prediction!r} ({confidence}%) {status}")

    except Exception as fatal:
        logger.critical(f"Fatal error at row {i}/{total}: {fatal}", exc_info=True)
        raise
    finally:
        if _owns_detector:
            detector.close()

    processed = i
    cancelled = cancel_event is not None and cancel_event.is_set()

    if cancelled:
        print(f"\nCancelled after {processed} row(s). Partial results saved to {output_path}")
    else:
        addressable = total - n_no_img
        print(
            f"\nDone: {n_match}/{total} matched "
            f"({100 * n_match / total:.1f}%) | "
            f"{n_no_img} sem cobertura GSV | "
            f"{n_error} error(s)"
        )
        if addressable:
            print(f"Effective accuracy (excl. no imagery): {100 * n_match / addressable:.1f}%")
        print(f"Saved to {output_path}")

    metrics.print_summary()
    if _owns_metrics:
        metrics_path = output_path.with_suffix(".metrics.json")
        metrics.save_json(metrics_path)
        print(f"Metrics saved to {metrics_path.name}")

    return output_path


# ── Public API ─────────────────────────────────────────────────────────────────

def run_from_sqlserver(
    filter_by: Literal["localidade", "freguesia", "concelho", "rua"],
    filter_value: str,
    output_path: str | Path,
    existing_csv: str | Path | None = None,
    detector_instance=None,
    cancel_event: Optional[threading.Event] = None,
    metrics: Optional[RunMetrics] = None,
) -> Path:
    output_path = Path(output_path).with_suffix(".csv")
    config      = Config()

    df = _query_sqlserver(filter_by, filter_value, config)

    already_processed: set[tuple[float, float]] = set()
    if existing_csv is not None:
        existing_csv = Path(existing_csv)
        if not existing_csv.exists():
            raise FileNotFoundError(f"Existing CSV not found: {existing_csv}")
        already_processed = _load_already_processed(existing_csv)
        print(f"Resuming from {existing_csv.name} — {len(already_processed)} rows already processed.")

    return _run_detection_on_df(
        df, output_path, already_processed, existing_csv,
        detector_instance=detector_instance,
        cancel_event=cancel_event,
        metrics=metrics,
    )


def run_batch_predictions(
    input_path: str | Path,
    output_path: str | Path,
    existing_csv: str | Path | None = None,
    detector_instance=None,
    cancel_event: Optional[threading.Event] = None,
    metrics: Optional[RunMetrics] = None,
) -> Path:
    input_path  = Path(input_path)
    output_path = Path(output_path).with_suffix(".csv")

    if not input_path.exists():
        raise FileNotFoundError(f"Input workbook not found: {input_path}")

    df = _read_excel_any(input_path)

    required_columns = {"NOME_COMPLETO_PORTA", "LATITUDE", "LONGITUDE"}
    missing = required_columns.difference(df.columns)
    if missing:
        raise ValueError(f"Missing required columns: {sorted(missing)}")

    already_processed: set[tuple[float, float]] = set()
    if existing_csv is not None:
        existing_csv = Path(existing_csv)
        if not existing_csv.exists():
            raise FileNotFoundError(f"Existing CSV not found: {existing_csv}")
        already_processed = _load_already_processed(existing_csv)
        print(f"Resuming from {existing_csv.name} — {len(already_processed)} rows already processed.")

    return _run_detection_on_df(
        df, output_path, already_processed, existing_csv,
        detector_instance=detector_instance,
        cancel_event=cancel_event,
        metrics=metrics,
    )


# ── Main ───────────────────────────────────────────────────────────────────────

def main():
    project_root = Path(__file__).resolve().parent
    ts           = datetime.now().strftime("%Y%m%d_%H%M%S")

    SOURCE       = "sqlserver"
    FILTER_BY    = "rua"
    FILTER_VALUE = "73789"

    if SOURCE == "sqlserver":
        safe_name  = FILTER_VALUE.replace(" ", "_")
        output_csv = project_root / f"predictions_{FILTER_BY}_{safe_name}_{ts}.csv"
        existing_csv = Path(r"C:\Users\mafapereira\OneDrive - NOS SGPS, S.A\Documents\door_number_detector_new\predictions_rua_73789_20260715_103500.csv")
        run_from_sqlserver(FILTER_BY, FILTER_VALUE, output_csv, existing_csv=existing_csv)
        return

    if SOURCE == "excel":
        input_workbook = project_root / "Portas_Teste.xlsx"
        output_csv     = project_root / f"Portas_Teste_predictions_{ts}.csv"
        existing_csv   = None
        run_batch_predictions(input_workbook, output_csv, existing_csv=existing_csv)
        return

    detector = DoorNumberDetector()
    latitude, longitude = 41.0897176190001, -6.80928270699997

    preview_image = detector.street_view.get_image(latitude, longitude)
    if preview_image is not None:
        print("Displaying fetched Street View image...")
        preview_image.show()

    result = detector.detect_door_number(latitude, longitude)

    print("\n" + "=" * 50)
    print("DETECTION RESULT")
    print("=" * 50)
    print(f"Latitude:    {result['latitude']}")
    print(f"Longitude:   {result['longitude']}")
    print(f"Door number: {result.get('door_number', 'N/A')}")
    print(f"Confidence:  {result.get('confidence', 0)}%")
    print(f"Observation: {result.get('observation', '')}")
    print(f"Status:      {'✓ Success' if result['success'] else '✗ Error'}")
    if not result["success"]:
        print(f"Error:       {result.get('error', 'Unknown')}")
    print("=" * 50)

    detector.close()


if __name__ == "__main__":
    main()
